### ISSUE TITLE
RNG state depends on number of processes

### ISSUE THREAD

**Issue by kostrzewa** [marcuspetschlies/cvc#1]
Would it not be better to use the "reproducible random numbers" mode in CVC such that all processes generate RNGs for the whole lattice but use only the ones for their local domain? This way, the random sources generated will always be independent of the number of processes.

**Comment by kostrzewa** [comment]
I've cooked something up in the https://github.com/kostrzewa/cvc-1/tree/cpff-bartek-devel branch.

This is a parallel version of MT19937_64 (64-bit Mersenne twister) which initialises one RNG per lattice site. It uses quite a bit of memory, of course. The RNG for a **local** lattice volume of 24c48 will take up about 1.6 GB to keep the state of all those generators.

Usage can be seen in

https://github.com/kostrzewa/cvc-1/blob/cpff-bartek-devel/tests/test_ParallelMT19937_64.cpp

The RNG itself is implemented here
https://github.com/kostrzewa/cvc-1/blob/cpff-bartek-devel/include/MT19937_64.hpp
and tested here (Google test)
https://github.com/kostrzewa/cvc-1/blob/cpff-bartek-devel/tests/gtest/test_MT19937_64.cpp

The parallel version here
https://github.com/kostrzewa/cvc-1/blob/cpff-bartek-devel/include/ParallelMT19937_64.hpp
https://github.com/kostrzewa/cvc-1/blob/cpff-bartek-devel/rng/ParallelMT19937_64.cpp

I've also added a little Stopwatch so timing stuff is fun. The generator is quite fast, 
Initialisation for a 32c128 global lattice takes less than a second (on the qbig frontend with gcc as the compiler).

It generates 50 16c32 spinors in 2 seconds on a single qbig core. Since there is one generator per lattice site, threading it is trivial and it scales well with the number of threads.

**Comment by kostrzewa** [comment]
This is not to displace your solution, but for very large lattices we need something which scales well and I think this just might.

**Comment by kostrzewa** [comment]
For a 96c192 global lattice with local lattices of 48^4 it takes only 10 seconds to initalise and 17 seconds to generate 50 full spinors. Initialisation scales linearly with the global volume and thus should be fine even on 128c256 while generation has perfect strong scaling as there is no communication. For realistic local lattices around 16c32 or so this should work great.

**Comment by kostrzewa** [comment]
I haven't done any quality tests yet. In particular I haven't tested all the initialisation seeds for uniqueness and this must be done, which will likely make the initialisation a little longer I'm afraid...

**Comment by kostrzewa** [comment]
Okay, my solution is ready and tested (in the sense that the MT19937_64 is initialised correctly) and that I've ensured two methods which guarantee that all seeds are unique on lattices at least up to 2^39 or so (larger than 512x256^3).

**Comment by kostrzewa** [comment]
I've also resolved the issues with long initialisation. By changing the default constructor of the underlying RNG to do nothing, which is unsafe, I am able to resize rather than reserve the vector of local RNGs because the default constructor is now trivial. I exposed the initialisation functions and can now initialise the local RNGs in a threaded loop because I don't need to rely on in-place construction.

**Comment by kostrzewa** [comment]
I've done some very simple statistical tests and don't seem to see correlations above what one would expect from sampling in [0,1] uniformly, neither in individual sequences, nor amongst sequences either on close-by lattice sites or a set of randomly selected lattice sites.

**Comment by marcuspetschlies** [comment]
current solution is reproducible for any mpi-layout;
other solutions can be added;
