### ISSUE TITLE
normalisation of Q_clover_phi

### ISSUE THREAD

**Issue by kostrzewa** [marcuspetschlies/cvc#11]
Looking at ```Q_clover_phi```, it seems that the clover term is kappa-normalised while the Hopping matrix is not, do I understand that correctly?

**Comment by kostrzewa** [comment]
Okay, actually we have to look at this slightly more accurately. So the tmLQCD inverter interface actually now returns a propagator in the field-theoretical normalisation. I remember that this was changed a long while ago.

See https://github.com/etmc/tmLQCD/blob/64ac1b3eb88299b5cd28ffc2bde7c31030974815/operator.c#L387 and https://github.com/etmc/tmLQCD/blob/64ac1b3eb88299b5cd28ffc2bde7c31030974815/quda_interface.c#L692.

This is not true of the solvers themselves, which of course work in the kappa normalisation. So when calling any of the solvers directly, the result is still in the kappa normalisation. This of course does not concern us since we don't do this.

This would then mean that the clover term and its inverse should be created by CVC in the field-theoretical normalisation, just like the hopping matrix. Would you agree?

**Comment by marcuspetschlies** [comment]
I am still trying to get the program to run on qbig for testing. Some 
segfault after quick comment around large parts of code ...

Am 27.11.18 um 17:46 schrieb Bartosz Kostrzewa:

**Comment by kostrzewa** [comment]
> https://github.com/kostrzewa/cvc-1/blob/cpff-bartek-devel/example_build_scripts/QBIG-Pascal/do_cmake_tmLQCD_QUDA.sh

If you want, you can try the cpff-bartek-devel branch and the provided build scripts (https://github.com/kostrzewa/cvc-1/blob/cpff-bartek-devel/example_build_scripts/QBIG-Pascal/do_cmake_tmLQCD_QUDA.sh). 

It seems to work fine for me after I added the checks for existing datasets to the h5 writer.

If you have *.h5 files in the working directory, delete them. Trying to create a dataset with an existing name fails and this then leads to a segfault, at least that's the second crasher that I had after the one with the input file reading that I told you about.

**Comment by marcuspetschlies** [comment]
Okay, so just to clarify, what does invert_direct_quda actually return ?

D^-1 source or ( 2 kappa D )^-1 source ?

Moreover, which gamma-basis are the returned propagators in ?

Am 27.11.18 um 17:46 schrieb Bartosz Kostrzewa:

**Comment by kostrzewa** [comment]
It returns D^{-1}. Internally it works in the (1 + kappa [...]) normalisation, but the propagator is mulitplied with 2*kappa before being returned, at least via the lib_wrapper interface (whether with GPU direct or not).

When calling the solvers directly, which we don't do, the propagator is returned unmodified.

Gamma basis is tmLQCD, as given by Shindler.

gamma_0
```
   0   0  -1   0
   0   0   0  -1
  -1   0   0   0
   0  -1   0   0
```

gamma_1
```
   0   0  0  -i
   0   0  -i  0
   0   i   0  0
   i   0   0  0
```

gamma_2
```
   0   0   0  -1
   0   0   1   0
   0   1   0   0
  -1   0   0   0
```

gamma_3
```
   0  0  -i  0
   0  0   0  i
   i  0   0  0
   0 -i   0  0
```

gamma_5 = g0g1g2g3
```
   1   0   0   0
   0   1   0   0
   0   0  -1   0
   0   0   0  -1
```

**Comment by marcuspetschlies** [comment]
I am always referring to calling invert_quda_direct.

So, quda/cuda works internally with the Shindler-basis?

Am 28.11.18 um 17:24 schrieb Bartosz Kostrzewa:

**Comment by marcuspetschlies** [comment]
With std CG I don't have a problem with the residuals; with 
invert_quda_direct, I do have a problem. So I am just trying to figure 
out, what the differences may be.

Am 28.11.18 um 17:28 schrieb Marcus Petschlies:

**Comment by kostrzewa** [comment]
Yes, invert_quda_direct and tmLQCD_invert should return the same thing.

QUDA works internally in the DeGrand-Rossi basis and the non-relativistic basis in some places. the MG is entirely in DeGrand-Rossi. Basis conversions are performed in various places such that invert_quda_direct should spit out propagators in the Shindler basis.

**Comment by marcuspetschlies** [comment]
Am 28.11.18 um 17:31 schrieb Bartosz Kostrzewa:
>
> Yes, invert_quda_direct and tmLQCD_invert should return the same thing.
>
> QUDA works internally in the DeGrand-Rossi basis and the 
> non-relativistic basis in some places. the MG is entirely in 
> DeGrand-Rossi. Basis conversions are performed in various places such 
> that invert_quda_direct should spit out propagators in the Shindler basis.
>
Where are these places?

**Comment by kostrzewa** [comment]
> Where are these places?

In quda_interface.c as well as deeper down in QUDA.

**Comment by kostrzewa** [comment]
> With std CG I don't have a problem with the residuals; with

Called via tmLQCD_invert ?

**Comment by marcuspetschlies** [comment]
Am 28.11.18 um 17:33 schrieb Bartosz Kostrzewa:
>
>     With std CG I don't have a problem with the residuals; with
>
> Called via tmLQCD_invert ?
>
Yes, that one.

**Comment by marcuspetschlies** [comment]
Am 28.11.18 um 17:33 schrieb Bartosz Kostrzewa:
>
>     Where are these places?
>
> In quda_interface.c as well as deeper down in QUDA.
>
Okay, I'll have a look into it.

**Comment by kostrzewa** [comment]
Okay, I just checked and there indeed seems to be a problem with invert_quda_direct. The QUDA calls themselves are fine, using the solver via tmLQCD_invert gives acceptable residuals:

```
GCR (restart): 1 iterations, <r,r> = 1.041462e-06, |r|/|b| = 5.750334e-06
GCR: 10 iterations, <r,r> = 1.372949e-07, |r|/|b| = 2.087846e-06
GCR: 11 iterations, <r,r> = 1.339444e-08, |r|/|b| = 6.521291e-07
GCR: 12 iterations, <r,r> = 1.016525e-09, |r|/|b| = 1.796513e-07
GCR: 13 iterations, <r,r> = 1.003527e-10, |r|/|b| = 5.644634e-08
GCR: 14 iterations, <r,r> = 7.857003e-12, |r|/|b| = 1.579428e-08
GCR: 15 iterations, <r,r> = 7.789484e-13, |r|/|b| = 4.973083e-09
GCR: 16 iterations, <r,r> = 6.078996e-14, |r|/|b| = 1.389272e-09
GCR: 17 iterations, <r,r> = 5.940081e-15, |r|/|b| = 4.342777e-10
GCR: 18 iterations, <r,r> = 4.699268e-16, |r|/|b| = 1.221480e-10
GCR: 19 iterations, <r,r> = 4.615462e-17, |r|/|b| = 3.828061e-11
GCR: number of restarts = 1
GCR: Convergence at 19 iterations, L2 relative residual: iterated = 3.831729e-11, true = 3.831729e-11
Solution = 66640
Reconstructed: CUDA solution = 70438.1, CPU copy = 70438.1
# QUDA: Done: 19 iter / 0.171481 secs = 1767.44 Gflops
# QUDA: time spent in reorder_spinor_fromQuda: 0.013698 secs
# Inversion done in 19 iterations, squared residue = 3.562495e-17!
# Inversion done in 2.01e+00 sec. 
# [check_residual_clover] propagator   0 norm diff even part = 5.624134e-06 / 1.440000e+02
# [check_residual_clover] propagator   0 norm diff odd  part = 5.636033e-06 / 1.440000e+02
```

**Comment by kostrzewa** [comment]
Must be some regression from all the changes that happened over the last couple of months.

**Comment by kostrzewa** [comment]
I'm confused since I checked the resulting propagators explicitly at the time, but it seems that something broke at some point..

**Comment by marcuspetschlies** [comment]
quda mg with invert works out for me.

quda mg with invert_quda_direct gives a problem.

Am 28.11.18 um 18:12 schrieb Bartosz Kostrzewa:

**Comment by kostrzewa** [comment]
"It's not a bug, it's a feature!"

The source is modified in the direct call, so the residual check fails. This was never a problem in previous applications because we did not reuse the source. I will modify the code tomorrow to create a copy of the source.

**Comment by kostrzewa** [comment]
Don't know how that affects your p2gg runs

**Comment by kostrzewa** [comment]
While the signature of the function does indicate that the source is not ```const```, the behaviour as it is can lead to nasty bugs such as this one, so I'd rather pay for the memcpy. I'll do it multithreaded so it will be a tiny overhead.

**Comment by marcuspetschlies** [comment]
Depends on how the source is modified.

In p2gg the source is not used after inversion, only the propagator is 
used for contractions.

But I will re-run some tests.

Am 28.11.18 um 18:53 schrieb Bartosz Kostrzewa:

**Comment by kostrzewa** [comment]
> Depends on how the source is modified.

The gamma basis is changed and it's brought into XYZT ordering.

**Comment by kostrzewa** [comment]
> In p2gg the source is not used after inversion, only the propagator is used for contractions. But I will re-run some tests. 

Sounds good.

**Comment by marcuspetschlies** [comment]
Actually, I always copy the source into a buffer and only the buffer 
goes to tmLQCD, so you can also leave it as it is now ( not loose speed 
); I can just switch to the original source for residual check.

Am 28.11.18 um 19:03 schrieb Bartosz Kostrzewa:

**Comment by marcuspetschlies** [comment]
Maybe one can add a flag preserve_source or so, to decide whether to or not.

Am 28.11.18 um 19:05 schrieb Marcus Petschlies:

**Comment by kostrzewa** [comment]
Works now. I will add the flag tomorrow.

```
Creating a GCR solver
GCR: 0 iterations, <r,r> = 3.149614e+04, |r|/|b| = 1.000000e+00
GCR: 1 iterations, <r,r> = 3.992718e+02, |r|/|b| = 1.125915e-01
GCR: 2 iterations, <r,r> = 2.676532e+01, |r|/|b| = 2.915127e-02
GCR: 3 iterations, <r,r> = 2.431627e+00, |r|/|b| = 8.786579e-03
GCR: 4 iterations, <r,r> = 1.920400e-01, |r|/|b| = 2.469262e-03
GCR: 5 iterations, <r,r> = 1.746904e-02, |r|/|b| = 7.447419e-04
GCR: 6 iterations, <r,r> = 1.458279e-03, |r|/|b| = 2.151749e-04
GCR: 7 iterations, <r,r> = 1.321276e-04, |r|/|b| = 6.476914e-05
GCR: 8 iterations, <r,r> = 1.160378e-05, |r|/|b| = 1.919425e-05
GCR: 9 iterations, <r,r> = 1.040469e-06, |r|/|b| = 5.747591e-06
GCR (restart): 1 iterations, <r,r> = 1.041462e-06, |r|/|b| = 5.750334e-06
GCR: 10 iterations, <r,r> = 1.372949e-07, |r|/|b| = 2.087846e-06
GCR: 11 iterations, <r,r> = 1.339444e-08, |r|/|b| = 6.521291e-07
GCR: 12 iterations, <r,r> = 1.016525e-09, |r|/|b| = 1.796513e-07
GCR: 13 iterations, <r,r> = 1.003527e-10, |r|/|b| = 5.644634e-08
GCR: 14 iterations, <r,r> = 7.857003e-12, |r|/|b| = 1.579428e-08
GCR: 15 iterations, <r,r> = 7.789484e-13, |r|/|b| = 4.973083e-09
GCR: 16 iterations, <r,r> = 6.078996e-14, |r|/|b| = 1.389272e-09
GCR: 17 iterations, <r,r> = 5.940081e-15, |r|/|b| = 4.342777e-10
GCR: 18 iterations, <r,r> = 4.699268e-16, |r|/|b| = 1.221480e-10
GCR: 19 iterations, <r,r> = 4.615462e-17, |r|/|b| = 3.828061e-11
GCR: number of restarts = 1
GCR: Convergence at 19 iterations, L2 relative residual: iterated = 3.831729e-11, true = 3.831729e-11
Solution = 66640
Reconstructed: CUDA solution = 70438.1, CPU copy = 70438.1
# QUDA: Done: 19 iter / 0.171906 secs = 1763.07 Gflops
# QUDA: time spent in reorder_spinor_fromQuda: 0.013847 secs
# QUDA: Total time for invert_quda_direct: 7.8746e-01
# [check_residual_clover] propagator   0 norm diff even part = 5.624134e-06 / 1.440000e+02
# [check_residual_clover] propagator   0 norm diff odd  part = 5.636033e-06 / 1.440000e+02
```

**Comment by kostrzewa** [comment]
I think we can regard this as resolved.
