### ISSUE TITLE
caveat: MPI_Wtime is unreliable with OpenMPI

### ISSUE THREAD

**Issue by kostrzewa** [marcuspetschlies/cvc#12]
@urbach @martin-ueding @marcuspetschlies 
I was just comparing timings on QBIG from my Stopwatch class (which uses std::chrono::steady_clock) and timings from tmLQCD / CVC, which use MPI_Wtime. Unfortunately, OpenMPI has a known bug (https://github.com/open-mpi/ompi/issues/3003) which causes MPI_Wtime to give unreliable time measurements. (basically it measures CPU cycles internally rather than using a steady clock without making sure to compute the correct normalisation and this really messes things up)

This is just to inform you not to trust MPI_Wtime when using OpenMPI, such as on QBIG. If in doubt, use the Stopwatch class or implement your own based on some steady clock.

**Comment by kostrzewa** [comment]
see https://github.com/kostrzewa/cvc-1/blob/cpff-bartek-devel/include/Stopwatch.hpp for the stopwatch class

**Comment by kostrzewa** [comment]
Note that I've checked (with an actual stopwatch) that my measurement is correct while MPI_Wtime reports whatever it feels like. In the cases that I've tested, it's about a factor of two:

```
Inverting to generate propagator fu_g05_px+0py+0pz+0
# QUDA: Using single prec. as sloppy!
# QUDA: Called _loadGaugeQuda
# QUDA: Theta boundary conditions will be applied to gauge field
# QUDA: Time for loadGaugeQuda: 7.0594e-01
# QUDA: Using MG!
# QUDA: Using EO preconditioning!
# QUDA: Time for loadCloverQuda: 4.1652e-02
# QUDA: mu = 0.005300001071, kappa = 0.140064500000, csw = 1.740000000000
# QUDA: Performing MG Preconditioner Setup
MG level 1 (GPU): Using curandStateMRG32k3a
MG level 1 (GPU): Allocated array of random numbers with rng_size: 45.56 MB
MG level 2 (GPU): Using curandStateMRG32k3a
MG level 2 (GPU): Allocated array of random numbers with rng_size: 0.24 MB
# QUDA: MG Preconditioner Setup took 86.108 seconds
# QUDA: time spent in reorder_spinor_toQuda: 0.188904 secs
GCR: Convergence at 40 iterations, L2 relative residual: iterated = 1.860872e-11, true = 1.860872e-11
# QUDA: Done: 40 iter / 1.227 secs = 805.838 Gflops
# QUDA: time spent in reorder_spinor_fromQuda: 0.068600 secs
# QUDA: Total time for invert_quda_direct: 8.9739e+01
STOPWATCH TMQLCD_INVERT 44.9318 seconds
min(44.9318) max(44.9318)
```

MPI_Wtime gives 89 seconds while only 45 seconds actually passed

**Comment by marcuspetschlies** [comment]
changed many places to gettimeofday to get walltime instead (nthread-dep.) cpu time
