### ISSUE TITLE
for twisted boundary conditions, random vector needs to be the innermost dimension

### ISSUE THREAD

**Issue by kostrzewa** [marcuspetschlies/cvc#2]
In order to save on redoing the MG setup for each change of theta, the random source must be the innermost dimension if multiple sources per gauge are to be used.

**Comment by marcuspetschlies** [comment]
I'll take it into consideration, when putting together the tbc-related prog.

Am 05.11.18 um 10:29 schrieb Bartosz Kostrzewa:

**Comment by marcuspetschlies** [comment]
current implementation in cpff_tbc_invert_contract uses minimal number of mg resets; but this depends on the number of fermion fields to be stored;
