### ISSUE TITLE
project.cpp cannot be compiled right now

### ISSUE THREAD

**Issue by kostrzewa** [marcuspetschlies/cvc#6]
See how https://stackoverflow.com/questions/18843017/why-can-braced-init-list-not-be-used-in-ternary-operator applies to line 656 of ```project.cpp``` in current ```cpff``` branch...

**Comment by kostrzewa** [comment]
This also means that ```shift[3]``` cannot be const.

**Comment by marcuspetschlies** [comment]
solved
